Top level verified LVS CLEAN--huzzaaaahhh

diff --git a/mag/Makefile b/mag/Makefile
--- a/mag/Makefile
+++ b/mag/Makefile
@@ -29,6 +29,41 @@ $(PROJECT_NAME).sim.spice: $(PROJECT_NAME).mag
 lvs.report: $(PROJECT_NAME).lvs.spice ../src/project.v
 	netgen -batch eval "set project $(PROJECT_NAME) ; source tcl/lvs_netgen.tcl"
 
+lvs_report_top: $(PROJECT_NAME).lvs.spice ../src/project.v
+	netgen -batch eval "set project $(PROJECT_NAME); source tcl/lvs_netgen_toplevel.tcl "
+
+lvs_top: lvs_report_top
+	@propOk=1; match=0; port=1; \
+    if grep -q "match uniquely" lvs.report; then \
+        match=1; \
+    fi; \
+    if grep -q "Property errors were found" lvs.report; then \
+        propOk=0; \
+    fi; \
+    if grep -q "failed pin matching" lvs.report; then \
+        match=0; \
+    fi; \
+    if grep -q "Final result: Netlists do not match" lvs.report; then \
+        match=0; \
+    fi; \
+    if grep -q "port errors" lvs.report; then \
+        port=0; \
+    fi; \
+    if grep -q "Final result: Circuits match uniquely\." lvs.report; then \
+        match=1; \
+    fi; \
+	if [ $$match -eq 1 ] && [ $$propOk -eq 1 ] && [ $$port -eq 1 ]; then \
+        echo "LVS OK"; \
+	    exit 0; \
+    else \
+        echo "LVS FAIL: match=$$match properties=$$propOk port=$$port"; \
+	    exit 1; \
+    fi
+
+
+
+
+
 lvs: lvs.report
 	@propOk=1; match=0; port=1; \
     if grep -q "match uniquely" lvs.report; then \
